global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'kf'

scrape_configs:

  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'node-exporter:9100'
